### PR TITLE
Thoth.Json and Thoth.Json.Net v2

### PR DESCRIPTION
**Pull request by MangelMaxime**
*When I say Thoth.Json it is grouping both Thoth.Json and Thoth.Json.Net.*

**⚠️  Important ⚠️**

Thoth.Json v2 will **only support Fable 2**. 

We already have some alpha packages released to test it on some production apps. But here we try to focus on presenting/defining the user experience.

Special thanks to:

- @alfonsogarciacaro for working on making the `Auto` decoder/encoder works.
- @glennsl for proposing the object builder style and answering my questions about it

# Introduction

I am creating this PR, so we (as a community) can discuss the next version of Thoth.Json. 

It's important to note that with Fable 2, Thoth.Json will be the recommanded way when working with JSON.

If you have any questions, ideas, please comment under this PR :)

### Tracking traveled path

The decoders are now tracking the traveled path.

```fs
// Old signature
type Decoder<'T> = obj -> Result<'T, DecoderError>

// New signature
type Decoder<'T> = string -> obj -> Result<'T, DecoderError>
```

This allow us to print the traveled path so when working with complexe JSON, we can better find the failing location. The path generated is a valid JSONPath so user can use tools like [JSONPath Online Evaluator](http://jsonpath.com/) to explore your JSON.

Example of error:

```fsharp
Error at: `$.user.firstname`
Expecting an object with path `user.firstname` but instead got:
{
    "user": {
        "name": "maxime",
        "age": 25
    }
}
Node `firstname` is unkown.
```

### Module based API

Both `Encode` and `Decode` modules are now decorated with `[<RequireQualifiedAccess>]`. This is needed to provide a consistant user experience and avoid problem where `FSharp.Core` function are override like `string`, `int`. 

```fsharp
// Old API
open Thoth.Json.Decode

type Point =
    { X : int
      Y : int }

    static member Decoder : Decoder<Point> =
        map2 (fun x y ->
                { X = x
                  Y = y } : Point)
             (field "x" int)
             (field "y" int)

// New API
open Thoth.Json

type Point =
    { X : int
      Y : int }

    static member Decoder : Decoder<Point> =
        Decode.map2 (fun x y ->
                { X = x
                  Y = y } : Point)
             (Decode.field "x" Decode.int)
             (Decode.field "y" Decode.int)
```

### Obsolete API

We are marking some APIs as Obsolete, in order to provide better readability and have a consistant naming with the `Auto`APIs.

#### Encode module

```fs
[<System.Obsolete("Please use toString instead")>]
let encode (space: int) (value: Value) : string = toString space value
```

#### Decode module

```fs
[<System.Obsolete("Please use fromValue instead")>]
let decodeValue (path : string) (decoder : Decoder<'T>) = fromValue path decoder

[<System.Obsolete("Please use fromString instead")>]
let decodeString (decoder : Decoder<'T>) = fromString decoder
```

### Removed APIs

The pipeline style has been removed. You should replace it with the [Object builder style](#object-builder).

We removed this API because it was easy to mess up the arguments order and it was verbose.

### Object builder

The object builder style replace the pipeline style.

The benefit is that new, you are constructing and decoding at the same time. Also, the API is easy to read:

- `get.Requried.Field (fieldName : string) (decoder : Decoder<'a>) : 'a`
- `get.Requried.At (fieldNames : string list) (decoder : Decoder<'a>) : 'a`
- `get.Optional.Field (fieldName : string) (decoder : Decoder<'a>) : 'a option`
- `get.Optional.At (fieldNames : string list) (decoder : Decoder<'a>) : 'a option`

```fsharp
open Thoth.Json

type User =
    { Id : int
      Name : string
      Email : string
      Followers : int }

    static member Decoder : Decoder<User> =
        Decode.object
            (fun get ->
                { Id = get.Required.Field "id" Decode.int
                    Name = get.Optional.Field "name" Decode.string
                            |> Option.defaultValue ""
                    Email = get.Required.Field "email" Decode.string
                    Followers = 0 }
            )
```

### Auto APIs

Because Thoth.Json is planned as a replacement for `ofJson` and `toJson` we are now providing `Auto` decoders and encoders support.

#### Decode module

The JSON can either be `PascalCase` or `camelCase`

```fs
open Thoth.Json

type User =
    { Id : int
      Name : string
      Email : string
      Followers : int }

let jsonCamelCase = """{ "id" : 0, "name": "maxime", "email": "mail@domain.com", "followers": 0 }"""
let user1 : Result<User, string> = Decode.Auto.fromString<User>(json, , isCamelCase=true)

let jsonPascalCase = """{ "Id" : 0, "Name": "maxime", "Email": "mail@domain.com", "Followers": 0 }"""
let user2 : Result<User, string> = Decode.Auto.fromString<User>(json)
```

By default the Auto decoders enforce you to deal with the `OK` and `Error` case. You can use exception based API if you prefer:

```fs
open Thoth.Json

type User =
    { Id : int
      Name : string
      Email : string
      Followers : int }

let jsonCamelCase = """{ "id" : 0, "name": "maxime", "email": "mail@domain.com", "followers": 0 }"""
let user : User = 
    try
        Decode.Auto.unsafeFromString<User>(json, , isCamelCase=true)
    with
        | ex -> reraise ex
```

#### Encode module

```fs
type User =
    { Id : int
      Name : string
      Email : string
      Followers : int }

let json =
    { Id = 0
      Name = "maxime"
      Email = "mail@domain.com"
      Followers = 0 }
    |> Encode.Auto.toString 4
```

### CODE REVIEW

**Comment by whitetigle** [comment]
What can I say? It's just great. As I use Thoth in all my projects, this new version seems cleaner, well thought and won't break the logic.  I am impatient to try the new features. Thanks for the good work!

**Comment by nojaf** [comment]
This looks good! 

Questions about the Auto API:
- Does it work with nested types?
- Are there any restrictions? 
- Does it require `[<CLIMutable>]` on the client or server?

**Comment by MangelMaxime** [comment]
@nojaf Yes this work for nested types. You can found some tests [here](https://github.com/MangelMaxime/Thoth/blob/a3bc388808dc176dc4bf2b4277355b670758bcf0/tests/Tests.Json.Decode.fs#L1215-L1249) *This is also to confirm we speak of the same thing :)*

I don't see any restrictions, and if there is any we will work to remove them.

I never used `[<CLIMutable>]`, so I would say no. We aren't passing an object between the server and the client. We are really working at JSON level, and then create the type instance using the API reflection.

**Comment by nojaf** [comment]
We are speaking about the same thing 😉 , thanks for the response @MangelMaxime.

**Comment by alfonsogarciacaro** [comment]
> Are there any restrictions?

Right now the auto converter cannot handle classes (only unions and records).

**Pull request merged**
