### PR TITLE
fix typos in toast documentation

### PR DESCRIPTION
**Pull request by selketjah**
fix typos in toast documentation

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Note for myself, when merging this PR, fix typos in the doc comments of the code too.

**Comment by selketjah** [comment]
I can do that too if you want

**Comment by MangelMaxime** [comment]
@selketjah Sure if you want to do it, will be appreciate. If not done, no problem will do it when merging. I just prefered to add a reminder so I didn't forget it :)

**Comment by selketjah** [comment]
Sure sure, a reminder for yourself ;-)
I think I got them all

**Comment by MangelMaxime** [comment]
Thank you

**Pull request merged**
