### PR TITLE
Add BasicPassword

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
I tried `{ myField with Type = "password" }` but it did not work.

**Comment by forki** [comment]
I did

    let myField =
        BasicInput
                .Create("name")
                .WithLabel("Name")
                .IsRequired()
                .WithDefaultView()
    { myField with Type = "password" }

**Comment by MangelMaxime** [comment]
You can't do that [`WithDefaultView` returns `FieldBuilder`](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Elmish.FormBuilder.BasicFields/Input.fs#L102) which isn't the representation of the [`Input.State`](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Elmish.FormBuilder.BasicFields/Input.fs#L14-L21).

In `FieldBuilder` `Type` refer to `basic-input`, `my-custom-type-field` which is used by the library to find the correct [`FieldConfig`](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Elmish.FormBuilder/Types.fs#L74-L87).

**Comment by MangelMaxime** [comment]
I am closing as my proposition should work in your case.

**Comment by forki** [comment]
Ok so you are adding that helper method?

Am Di., 8. Jan. 2019, 09:53 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
You should already have it available: https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Elmish.FormBuilder.BasicFields/Input.fs#L130-L131

**Pull request closed without merging**
